### ISSUE TITLE
StackdriverExporter with application default credentials crashes

### ISSUE THREAD

**Issue by ocervell** [census-instrumentation/opencensus-python#304] opened 2018-09-10 21:59 UTC
I noticed that currently, if we're using the application default credentials, the `StackdriverExporter` ends up crashing because of [this issue](https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/211) in `google-auth-library-python` and the only way to make it work again is to restart the background thread.

The tracing collection goes fine for a while, and then starts failing in loops with:
```
...
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/client.py", line 212, in __init__
    Client.__init__(self, credentials=credentials, _http=_http)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/client.py", line 125, in __init__
    credentials, _ = google.auth.default()
  File "/usr/local/lib/python2.7/dist-packages/google/auth/_default.py", line 286, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials.
```

**Comment by ocervell** [comment] 2018-11-09 21:01
I haven't seen this for a while, not sure if still a problem. My PR #291 was unrelated I believe.

**Comment by c24t** [comment] 2018-11-12 20:07
It doesn't look like it's fixed in the auth library, and I don't see any changes in the exporter or transport that would have fixed this since you opened the ticket. That said, I haven't run into this issue yet using app default credentials in e.g. the demo app.

If you have steps to reproduce it or a full stack trace we can try restarting the background thread on known errors like this, but it may be worth trying to fix the issue in the auth library instead.

**Comment by songy23** [comment] 2019-01-22 21:43
Not reproducible - see previous comments.

**Closed by songy23** 2019-01-22 21:43 UTC
