### ISSUE TITLE
Allow users to use custom metric name prefix for Stackdriver

### ISSUE THREAD

**Issue by mayurkale22** [census-instrumentation/opencensus-python#310] opened 2018-09-13 21:00 UTC
Add a way to override metric name prefix. Today, OpenCensus only supports "custom.googleapis.com" (https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/stats/exporters/stackdriver_exporter.py#L352), but Stackdriver supports more prefixes (https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors#MetricDescriptor).

Counterpart in Java: https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java#L250

Equivalent to census-instrumentation/opencensus-java#1057.

**Comment by songy23** [comment] 2018-09-13 21:28
census-instrumentation/opencensus-go#583 only added support for customizing `Display Name`, is that what we want? If not, I think the equivalent change should be https://github.com/census-instrumentation/opencensus-java/pull/1057.

**Comment by mayurkale22** [comment] 2018-09-13 21:30
@songy23 Yes, Corrected.

**Comment by songy23** [comment] 2018-09-19 18:34
Duplicate of https://github.com/census-instrumentation/opencensus-python/issues/311.

**Closed by songy23** 2018-09-19 18:34 UTC
Labels: enhancement, stats
