### ISSUE TITLE
Is it expected when using logger.error or logger.exception, the messages are treated as trace?

### ISSUE THREAD

**Issue by star286** [census-instrumentation/opencensus-python#1005] opened 2021-01-27 07:04 UTC
Environment:

python 3.8, opencensus-ext-azure 1.0.7

**Steps to reproduce.**
the code as below:

```
logger.error("it is an error")
logger.exception("it is an exception")
```

**What is the expected behavior?**
The messages which are logged by logger.error or logger.exception should be treated as exceptions in application insights.

**What is the actual behavior?**
These messages are treated as trace in application insights

Is this an expected behavior? and any workaround to fix this?

**Comment by m1nkeh** [comment] 2021-01-27 11:17
yep, this caught me out too!

**Comment by lzchen** [comment] 2021-01-27 16:55
`logger.error` is not always an exception. `error` is a specific Python [logging level](https://docs.python.org/3/library/logging.html#logging-levels) and users may use it as a mechanism to filter what kind of logs they want to see.

`logger.exception` ARE treated as exceptions, you simply need to log them within an actual exception for them to show in App insights.

**Comment by lzchen** [comment] 2021-01-27 17:04
There seems to be a bug where if user uses `logger.exception` with no actual exception, no log is sent. Will be making a fix for this.

**Closed** 2021-01-27 19:37 UTC
Labels: azure, bug

**Comment by empowerNate** [comment] 2024-03-19 19:27
It seems like this is still not working - when I use logging.exception, it logs as a trace and not as an exception in app insights.

**Comment by lzchen** [comment] 2024-03-19 19:46
We have changed this so that users must use `logger.exception` with an actual exception, otherwise it is treated as a `trace` so that is indeed expected behavior.

**Comment by empowerNate** [comment] 2024-03-20 02:18
Hmm ok, I tried this and I don't think it worked, but can try again.

```
try:
    ...
except Exception as e:
    logging.exception(e)
```

is that not the right way to do it?

**Comment by lzchen** [comment] 2024-03-20 21:03
@empowerNate 

Yes that is exactly how you do it. If an exception is raised in your try block, the exception should be caught and then logged with `logger.exception`. 

Be sure to use the `logger` that you added `AzureLogHandler` to, not `logging` which is the module. See [this example](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/examples/logs/error.py) for specifics.

**Comment by empowerNate** [comment] 2024-03-20 21:33
Ah, that's it - I didn't add the handler.
