### ISSUE TITLE
Duplicated messages in Azure Application Insights

### ISSUE THREAD

**Issue by abdellahrami** [census-instrumentation/opencensus-python#1088] opened 2021-11-09 15:19 UTC
## Environment
Python 3.9.6 - 64 bit Windows 10
pip 21.3.1
opencensus==0.8.0
opencensus-context==0.1.2
opencensus-ext-azure==1.1.0

## Steps to reproduce
I tried running the following code in mutliple places including new venvs that have just the opencensus-ext-azure library 

```python
import logging

from opencensus.ext.azure.log_exporter import AzureLogHandler

logger = logging.getLogger(__name__)

handler = AzureLogHandler(connection_string="<My-InstrumentationKey>")
logger.addHandler(handler)

properties = {"custom_dimensions": {"key_1*****": "value_1", "key_2********": "value_2"}}
logger.error("Error 12 : Hello, World!", extra=properties)
```

## What is the expected behavior?
We expect to see 1 message in the traces table in application insights

## What is the actual behavior?
Duplicate records with the exact timestamp : 
![image](https://user-images.githubusercontent.com/37387672/140951360-4f0f7b47-d15d-421a-bdba-71f6503b2eb4.png)

## Additional info
I am aware of the issue #901 and i think it's not the same cause.

**Comment by lzchen** [comment] 2021-11-09 17:23
Are you using Databricks notebooks by any chance?

**Comment by abdellahrami** [comment] 2021-11-09 17:24
No

**Comment by vgofaizen** [comment] 2021-11-09 19:25
We are also running into this

**Comment by lzchen** [comment] 2021-11-10 17:42
@abdellahrami 
Strange, I am not able to reproduce the behavior on my machine. This problem should only occur when there are multiple exporters added to the log handler.

**Comment by abdellahrami** [comment] 2021-11-10 18:36
@lzchen okey thanks, I'll see if its caused more by the AppInsight side, because when I test it locally I get only one log.

**Comment by corticalstack** [comment] 2021-11-29 23:05
Just to add' I've been seeing duplicate entries in Application Insights as well. It made me go check my front-end app to ensure no looping in UI handling. Perhaps its an App Insights issue?

**Comment by sudivate** [comment] 2021-12-02 02:29
@lzchen I'm using Databricks notebooks and had a similar experience of duplicate metrics. Is there a workaround to clear the queue immediately after recording a metric?

**Comment by lzchen** [comment] 2021-12-02 19:45
@sudivate 
Are you getting duplicate metrics or duplicated logs?

**Comment by sudivate** [comment] 2021-12-02 19:51
@lzchen duplicate metric and almost all the time.

**Comment by simonsben** [comment] 2021-12-22 17:01
I have the same problem, sometimes reporting the same one 10+ times

**Comment by corticalstack** [comment] 2021-12-22 20:29
@simonsben seen that many time repeat of same telemtry as well

**Comment by lzchen** [comment] 2022-01-03 16:14
@simonsben @corticalstack 
Could you post an screenshot of the duplicate telemetry and how you are sending metrics?

**Comment by corticalstack** [comment] 2022-01-03 16:23
@lzchen hope this helps

![image](https://user-images.githubusercontent.com/3995321/147953982-93ea9635-d1b7-4462-8bf6-6a5cc50eef3a.png)


```
from opencensus.ext.azure.log_exporter import AzureLogHandler
from opencensus.ext.azure.common import utils
from opencensus.ext.azure.common.protocol import Data, Envelope, MetricData
import logging

logger = logging.getLogger(__name__)
```


```
 def _log_query(self, **kwargs):
            query = {}

            query["user"] = st.session_state.http_headers["logged_in_user_name"]

            if "title_term" in kwargs:
                if kwargs["title_term"]:
                    query["title_term"] = kwargs["title_term"]
            
            if "authors_term" in kwargs:
                if kwargs["authors_term"]:
                    query["authors_term"] = kwargs["authors_term"]

            if "doi_term" in kwargs:
                if kwargs["doi_term"]:
                    query["doi_term"] = kwargs["doi_term"]
            
            if "abstract_term" in kwargs:
                if kwargs["abstract_term"]:
                    query["abstract_term"] = kwargs["abstract_term"]

            properties = {"custom_dimensions": query}
            logger.info("Literature archive query", extra=properties)
```

**Comment by lzchen** [comment] 2022-01-03 17:38
@corticalstack 
Where are you instantiating the `AzureLogHandler`? Are you running this on a notebook? Standalone python app?

**Comment by corticalstack** [comment] 2022-01-03 18:27
@lzchen in a Python app - using the Streamlit framework to be exposed as a web app within a containerised Azure App Service

**Comment by lzchen** [comment] 2022-01-05 15:38
@corticalstack 
Where are you instantiating the `AzureLogHandler`? Do you still get duplicate messages when running locally (not deployed on App Service)?

**Comment by ThadRasmussen** [comment] 2022-01-05 21:32
Just going to throw in my two cents, as I chased the duplicate _traces_ for quite awhile.  When using a custom package to initialize a `AzureLogHandler` and  `AzureExporter`, such that it could be shared across multiple projects, the _traces_ were always duplicated while the _requests_ were as expected.  The only way I have discovered to make sure that the _traces_ were only captured once was to use a `yml` configuration with the `logging.config.dictConfig`, like follows:
```yaml
version: 1
disable_existing_loggers: False

formatters:
  azure:
    format: '[%(asctime)s] %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S'
handlers:
  azureDefault:
    class: opencensus.ext.azure.log_exporter.AzureLogHandler
    formatter: azure
root:
  level: INFO
  handlers: [ azureDefault]
```
Then used that file like follows:
```pythong
def setup_logging(logging_file: Path):
    config_dict = yaml.safe_load(logging_file.read_text())
    logging.config.dictConfig(config_dict)
    logging.Formatter.converter = time.gmtime

setup_logging(logging_file)  # Absolute path of yml file
```

The only drawback that I have now is that the `AzureLogHandler` is not able to call the  **add_telemetry_processor** callback.  I hope that helps someone

**Comment by corticalstack** [comment] 2022-01-06 09:26
@lzchen duplicates logged when running python script directly on local development machine as localhost, no containers etc....

![image](https://user-images.githubusercontent.com/3995321/148360392-23f79883-b7c1-4668-86a9-64d6c8d90873.png)

**Comment by lzchen** [comment] 2022-01-07 23:04
@corticalstack 

This usually only occurs when the `AzureLogHandler` is added to the root logger multiple times. Please share where you are doing this.

**Comment by corticalstack** [comment] 2022-01-10 16:13
@lzchen adding of the AzureLogHandler multiple times to the root logger was indeed the issue for me (even though I had it wrapped arounf check of streamlit session state, but thats another issue).

Resolved by checking length of logger handlers. Thanks!

```
if len(logger.handlers) == 0:
  logger.addHandler(AzureLogHandler(connection_string=APPI_CONNECT_STRING))
```

**Closed** 2022-01-25 22:30 UTC
Labels: bug
