### ISSUE TITLE
HTTP_ROUTE not always set when exporting to Azure

### ISSUE THREAD

**Issue by paul-ciobanu** [census-instrumentation/opencensus-python#1129] opened 2022-06-15 05:11 UTC
I have a Flask application running in a container in AKS.
I notice that randomly some requests are missing the `url_rule` in the `name` column in Azure Application Insights in our prod environment.

In the image below, all 3 requests are to the same `POST /<string:extractor_id>/<string:name>` endpoint:
![image](https://user-images.githubusercontent.com/36033740/173740586-a9a93ade-ea00-4298-be21-f25d5358c27e.png)

**Describe your environment.** 
Python = 3.8

Package versions
```
Flask = "^2.1.2"
opencensus = "^0.8.0"
opencensus-context = "^0.1.2"
opencensus-ext-azure = "^1.1.4"
opencensus-ext-flask = "^0.8.0"
opencensus-ext-gevent = "^0.1.0"
opencensus-ext-logging = "^0.1.1"
opencensus-ext-requests = "^0.7.6"
opencensus-ext-sqlalchemy = "^0.1.3"
```

**Steps to reproduce.**
I wasn't able to reproduce the issue locally.
I tried canceling the incoming request, adding delays, but each time the `url_rule`/`HTTP_ROUTE` is properly set.

**What is the expected behavior?**
all requests should have `name` column to have the correct format `{HTTP_METHOD } {HTTP_ROUTE}` (like the last row in the above image)

**What is the actual behavior?**
`name` column only has the HTTP_METHOD set, but not the `HTTP_ROUTE` (see [here](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-flask/opencensus/ext/flask/flask_middleware.py#L192))

**Additional context.**
I read that if an exception is caused in one of the `after_request_funcs` registered in `Flask`, then the other `after_request` callbacks won't be executed, but in this case I only have [FlaskMiddleware](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-flask/opencensus/ext/flask/flask_middleware.py#L50) installed as a middleware in my application.

As a side-effect of this issue, I think that `0` is set as a result code.
Looking in the container logs, it seems that `Flask` returns `200`
![image](https://user-images.githubusercontent.com/36033740/173741088-6b7e2ec5-d3ee-4a32-ad80-570a78fd2ff2.png)

**Comment by paul-ciobanu** [comment] 2022-06-15 18:26
`or, for some reason, those specific calls do not have url_rule or status_code populated` - what could cause only a subset of calls to the same endpoint to not have url_rule or status_code populated? 
If they were missing, I would expect the call to also be missing the host, method, path and url, which are set by `_before_request`...

There are no `Failed to trace request` messages in the python logs

**Comment by lzchen** [comment] 2022-06-15 18:48
What do your "custom_dimensions" field look like for those pieces of telemetry?

**Comment by paul-ciobanu** [comment] 2022-06-15 19:11
customDimensions["request.name"] = `POST /725d33ed-246c-4561-ba9d-30be8ea5dc9c/name`
customDimensions["request.url"] = `http://custom.trafficmanager.net/725d33ed-246c-4561-ba9d-30be8ea5dc9c/name`

which maps to
```
         elif HTTP_PATH in sd.attributes:
                data.properties['request.name'] = data.name + \
                    ' ' + sd.attributes[HTTP_PATH]
```
from [AzureExporter](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py#L130-L132)

**Comment by paul-ciobanu** [comment] 2022-06-20 17:07
@lzchen any other ideas that I can try?

**Comment by lzchen** [comment] 2022-06-21 00:03
@paul-ciobanu 
I'm not able to reproduce this on my local machine. How often is this issue happening? It will be difficult to diagnose the root cause if it cannot be seen in your prod environment frequently. As well, if you don't see any error message in your logs, this means that `_before_request` and `_after_request` hooks most likely did not return an error. Is it possible some requests to your response are returning an invalid response?

**Comment by paul-ciobanu** [comment] 2022-07-06 16:20
I tried multiple responses and I can never reproduce when running the code locally
I'm running out of ideas how to try to reproduce this...

**Comment by lzchen** [comment] 2022-07-06 16:35
@paul-ciobanu 

I will be closing this issue for now. Feel free to comment if you are able to reproduce it consistently.

**Closed by lzchen** 2022-07-06 16:35 UTC
Labels: bug, azure

**Comment by catalinapopa-uipath** [comment] 2023-10-03 06:34
Hi @lzchen 

I've manage to reproduce this issue constantly locally.

1. I have an endpoint which inserts data into database. (important note: there is a unique constraint on the table)
2. Started `gunicorn` with 1 workers and 120s timeout.
3. Created a test with 4 threads calling the same endpoint (duplicate data). 
 
The gunicorn worker seems blocked and after timeout it restarts and requests appear with `resultCode = 0` and name not populated in appins.
`[CRITICAL] WORKER TIMEOUT (pid:13522)`

![image](https://github.com/census-instrumentation/opencensus-python/assets/106528249/d42e0085-cca6-4987-81d0-d60242fa76be)

Do you have any update on this?
