### ISSUE TITLE
type object 'CountAggregation' has no attribute 'aggregation_data'

### ISSUE THREAD

**Issue by migibert** [census-instrumentation/opencensus-python#422] opened 2018-12-03 16:36 UTC
Hello,

I tried to define a custom metric to count requests handled by one of my endpoints (I use django). I followed the quickstart in the README.md but faced an issue with CountAggregation.

Here is the code I use in my endpoint:
```
    def __init__(self, project_id):
        self.stats_recorder = stats_module.Stats().stats_recorder
        view_manager = stats_module.Stats().view_manager
        view_manager.register_view(Metrics.MY_VIEW)
        stackdriver_options = stackdriver.Options(project_id=project_id, metric_prefix=Metrics.METRIC_PREFIX)
        stackdriver_exporter = stackdriver.new_stats_exporter(stackdriver_options)
        view_manager.register_exporter(stackdriver_exporter)

    def record(self, tag1, tag2):
        measure_map = self.stats_recorder.new_measurement_map()
        measure_map.measure_int_put(Metrics.MY_MEASURE, 1)
        tag_map = tag_map_module.TagMap()
        tag_map.insert(Metrics.TAG_1, tag_value_module.TagValue(tag1))
        tag_map.insert(Metrics.TAG_2, tag_value_module.TagValue(tag2))
        measure_map.record(tag_map)
```

I joined the Traceback below:

```
Traceback (most recent call last):
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mikael/Documents/projects/application/api/views/utils.py", line 22, in decorator
    return view_func(*args, **kwargs)
  File "/home/mikael/Documents/projects/application/api/decorator.py", line 23, in decorator
    return view_func(*args, **kwargs)
  File "/home/mikael/Documents/projects/application/api/views/metrics_view.py", line 69, in ...
  File "/home/mikael/Documents/projects/application/api/metrics.py", line 37, in ...
    measure_map.record(tag_map)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/opencensus/stats/measurement_map.py", line 87, in record
    attachments=self.attachments
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/opencensus/stats/measure_to_view_map.py", line 109, in record
    attachments=attachments)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/opencensus/stats/view_data.py", line 89, in record
    self.view.aggregation.aggregation_data)
AttributeError: type object 'CountAggregation' has no attribute 'aggregation_data'
```

**Comment by migibert** [comment] 2018-12-03 16:39
I also tried to change my Aggregation to SumAggregation and hit the same problem 
`AttributeError: type object 'SumAggregation' has no attribute 'aggregation_data'`

**Comment by c24t** [comment] 2018-12-03 21:55
Hi @migibert, thanks for opening the issue. I can't reproduce this particular error, but I am seeing errors from the stackdriver monitoring client trying to export count and sum aggregations.

What versions of `opencensus` and `google-cloud-monitoring` are you on? Can you run the [stackdriver stats example](https://github.com/census-instrumentation/opencensus-python/blob/master/examples/stats/exporter/stackdriver.py) (note that you'll have to change "opencensus-node" to your own project ID to send the stat to stackdriver).

**Comment by migibert** [comment] 2018-12-04 12:31
Hey @c24t , thanks for looking at my issue.

I am using:
- opencensus==0.1.9
- google-cloud-monitoring==0.31.0

Just tested the example and it works well... Maybe because of Distribution aggregation or maybe I miss something on my setup...

**Comment by migibert** [comment] 2018-12-04 13:21
I adapted the example code with a CountAggregation and got another error...

My code
```
import time
import random
from opencensus.stats import aggregation as aggregation_module
from opencensus.stats.exporters import stackdriver_exporter as stackdriver
from opencensus.stats import measure as measure_module
from opencensus.stats import stats as stats_module
from opencensus.stats import view as view_module
from opencensus.tags import tag_key as tag_key_module
from opencensus.tags import tag_map as tag_map_module
from opencensus.tags import tag_value as tag_value_module

MY_KEY = tag_key_module.TagKey("my.org/keys/mykey")
REQUESTS_MEASURE = measure_module.MeasureInt("my.org/measure/requests", "count of requests", "1")
REQUESTS_VIEW_NAME = "my.org/views/requests"
REQUESTS_COUNT = aggregation_module.CountAggregation()
REQUESTS_VIEW = view_module.View(REQUESTS_VIEW_NAME, "Requests count", [MY_KEY], REQUESTS_MEASURE, REQUESTS_COUNT)

stats = stats_module.Stats()
view_manager = stats.view_manager
stats_recorder = stats.stats_recorder

exporter = stackdriver.new_stats_exporter(stackdriver.Options(project_id="<my_project_id>"))
view_manager.register_exporter(exporter)

# Register view.
view_manager.register_view(REQUESTS_VIEW)

# Record the processed video size.
tag_value = tag_value_module.TagValue('test')
tag_map = tag_map_module.TagMap()
tag_map.insert(MY_KEY, tag_value)
measure_map = stats_recorder.new_measurement_map()
measure_map.measure_int_put(REQUESTS_MEASURE, 1)

measure_map.record(tag_map)
```

And the error
```
ERROR:root:StackdriverStatsExporter failed to emit data.Dropping 1 objects from queue.
Traceback (most recent call last):
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/opencensus/common/transports/async_.py", line 105, in _thread_main
    self.exporter.emit(data)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 145, in emit
    self.handle_upload(view_data)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 157, in handle_upload
    self.upload_stats(view_data)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 166, in upload_stats
    request[CONS_TIME_SERIES])
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/google/cloud/monitoring_v3/gapic/metric_service_client.py", line 897, in create_time_series
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 61, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/home/mikael/Documents/projects/application/venv/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
InvalidArgument: 400 Request was missing field timeSeries[0].points[0].int64Value.
```

**Comment by c24t** [comment] 2018-12-04 21:55
I'm seeing the same thing, looks like a bug in the stackdriver stats exporter. Looking into it now.

**Comment by songy23** [comment] 2019-01-22 21:40
Is this fixed in https://github.com/census-instrumentation/opencensus-python/pull/438?

**Comment by c24t** [comment] 2019-01-22 21:42
It should be fixed, @migibert please take a look and let us know if this works for you.

**Comment by migibert** [comment] 2019-01-23 07:51
Sure, I'll take a look next week, this one is pretty busy on my side

**Comment by c24t** [comment] 2019-02-12 19:17
@migibert feel free to reopen if you still see any problems here.

**Closed by c24t** 2019-02-12 19:17 UTC
